server:
  port: 8091

spring:
  application:
    name: consumer
  cloud:
    #nacos
    nacos:
      discovery:
        server-addr: ds.com:8848
        #  namespace: ds-spring-cloud-alibaba
        #  group: dev
        #  username: nacos
        #  password: nacos
        namespace: ds-spring-cloud-alibaba       #新建用户只能注册服务到对应的namespace下
        group: dev
        username: ds
        password: ds
    #sentinel
    sentinel:
      transport:
        port: ${server.port}
        dashboard: ds.com:8080

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'