server:
  port: 8081

spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: ds.com:8848
        #  namespace: ds-spring-cloud-alibaba
        #  group: dev
        #  username: nacos
        #  password: nacos
        #namespace: ds-spring-cloud-alibaba
        #group: dev
        #username: ds
        #password: ds

    sentinel:
      transport:
        port: ${server.port}
        dashboard: ds.com:8080

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'